"""empty message

Revision ID: bf8a5a6ad90f
Revises: a7a6db9b70bc
Create Date: 2022-08-20 22:44:47.058739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8a5a6ad90f'
down_revision = 'a7a6db9b70bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artists', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    op.add_column('Artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venues', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venues', 'seeking_description')
    op.drop_column('Venues', 'seeking_talent')
    op.drop_column('Artists', 'seeking_venue')
    op.drop_column('Artists', 'seeking_description')
    # ### end Alembic commands ###
